apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-local
spec:
  rules:
  - host: argocd.toannc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80

